services:
  app:
    image: python-scraping
    container_name: python-scraping
    build: .
    ports:
      - 80:80
    volumes:
      - ./src:/app/src
      - ./csv:/app/csv
    working_dir: /app/src
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    tty: true
